### ISSUE TITLE
[BUG] snoozing by right-click tab menu does not close the tab

### ISSUE THREAD

**Issue by mkeroppi** [rohanb10/snoozz-tab-snoozing#10]
## Description

snoozing by right-click tab menu does not close the tab

## Expected Behavior

closes the snoozed tab as consistent with snoozing by other means

## Actual Behavior

does not close tab

## Your Device
* Browser and version: firefox
* OS:
* Device Resolution (UI related bugs only)

**Comment by rohanb10** [comment]
Fixed https://github.com/rohanb10/snoozz-tab-snoozing/commit/30d62432aa36ac5402cd5e4ae7e0745244366a11

**Comment by rohanb10** [comment]
Bug has been fixed in v2.2.0
