### ISSUE TITLE
[BUG] numerous dashboard page openings when clicking on a pop-up

### ISSUE THREAD

**Issue by mkeroppi** [rohanb10/snoozz-tab-snoozing#16]
## Description
clicking on a pop-up while there are other popups open up the dashboard many times

## Expected Behavior
dashboard opening one time

## Actual Behavior
open up the dashboard many times

## How to Reproduce (if applicable)
occasional behavior when there are many pop-ups (e.g., a number of pages waking up or snoozing)

## Your Device
* Browser and version: Firefox 82.0.0.3
* OS: Windows 10
* Device Resolution (UI related bugs only)

## Which Page

popup/dashboard

**Comment by rohanb10** [comment]
To be clear, do multiple dashboard tabs open up when you click on a single notification? If this is the case, then this commit will fix it e992f4865a57d52298c2836c63f9712e2cabd520

If not, then I can do a deeper dive and make sure two instances of the dashboard never open in the same window

**Comment by rohanb10** [comment]
Updated in v2.3.2. Will close if issue does not pop up again in a few days

**Comment by mkeroppi** [comment]
Sort of fixed for me.  I can see that it's still opening a number of tabs but it's closing the extra tabs almost immediately after.

**Comment by rohanb10** [comment]
Can you clarify some things for me so I can debug this further?

1. On Windows, if you have multiple tabs waking up at the same time do you see multiple notifications? (I use a mac and it only shows you the notification that was queued last).
2. If you see multiple notifications, are you clicking on only a single one and seeing the dashboard open many times?
3. Does this behaviour also happen when you have a single notification and open and you click on it?

The extension has always been designed to only have one page open (Either settings or dashboard). If you already have a dashboard tab open, and try opening a new one it will just redirect you the existing one. If you do manage to open it (as you mentioned above), it will check for other instances of itself and close immediately.

**Comment by mkeroppi** [comment]
Sorry the comment was meant for another bug: https://github.com/rohanb10/snoozz-tab-snoozing/issues/11

This bug is fixed for me.

**Comment by concese** [comment]
I'm not sure if this should be reported still on this one, or on a new one. 
I was following this bug report because, with me, it was opening several duplicate tabs, but not of the dashboard. 

Now, if I have several tabs waking at the same time, I do get the several notifications. Clicking on any of them, sends me to the dashboard, but I think before it was sending to the respective tab.

**Comment by rohanb10** [comment]
@concese you are using windows correct?

As far as I remember, clicking on a notification  would always open the dashboard page. But now that seems dumb, I’ll change the behaviour to switch to the clicked tab

**Comment by concese** [comment]
@rohanb10 thanks for the quick check. 
YEs, windows 10 (sorry forgot to mention). 
If you prefer I create a new request, let me know.
