### ISSUE TITLE
[BUG] next Monday skips a week when on Sunday

### ISSUE THREAD

**Issue by mkeroppi** [rohanb10/snoozz-tab-snoozing#17]
## Description
Next Monday for today (11/15/20) is 11/23/20, skipping 11/16/20

## Expected Behavior
I'd think it should be the "next" Monday after today, not the Monday next week.

## Actual Behavior
Monday next week

## How to Reproduce (if applicable)
snooze to "next Monday"

## Your Device
* Browser and version: Firefox 82.0.3
* OS: Windows 10
* Device Resolution (UI related bugs only)

**Comment by rohanb10** [comment]
c8cfc88d1e90410564a9b29c5b4ebfcc93db5b47 fixed

**Comment by rohanb10** [comment]
Updated in v2.3.2
