### ISSUE TITLE
[BUG] keyboard shortcut and right-click context menu no longer works

### ISSUE THREAD

**Issue by mkeroppi** [rohanb10/snoozz-tab-snoozing#18]
## Description

keyboard shortcut and right-click context menu no longer works

## Expected Behavior

keyboard shortcut and right-click context menu works
## Actual Behavior

keyboard shortcut and right-click context menu no longer works

## How to Reproduce (if applicable)

use v2.3.2

## Your Device
* Browser and version: Firefox 83.0
* OS: Windows 10
* Device Resolution (UI related bugs only)

**Comment by rohanb10** [comment]
89763f76d58bad4bb95c01dccce146a94f7c2de3 fixed.

v2.3.2.1 is out on Firefox. Chrome should be in review
