### ISSUE TITLE
Custom snoozes such as "3 Hours" or "2 Days"?

### ISSUE THREAD

**Issue by orschiro** [rohanb10/snoozz-tab-snoozing#19]
Hi Rohan, 

Thanks for developing this extension, this is really cool! :)

Wondering if you can think of a setting by which the user can define custom snoozes such as in "3 Hours" or in "2 Days"?

Thoughts?

**Comment by concese** [comment]
On another similar extension I used before, it had a default "later" which would snooze for 3h

**Comment by orschiro** [comment]
You mean Snooze Tabby? Great extension by the way to get some inspiration
from!

 Still using it until Snoozz has all the features that Tabby has, among
this one. :)

**Comment by concese** [comment]
No, it's Snooze Tabs. 
I also kept both for a while, but recently turned it off. 
One of the reasons to switch was the amount of permissions the other was requesting, for the same tasks.

**Comment by orschiro** [comment]
I see but really the custom snoozes is what still keeps me with Tabby. See below:

![image](https://user-images.githubusercontent.com/170947/104019436-d9d0b500-51bb-11eb-96cb-2b8beb50a812.png)

**Comment by hodanli** [comment]
i really like to see this feature too.

**Comment by rohanb10** [comment]
Just a quick Q for all you guys requesting this. I'm thinking of adding the ability to define custom preset times in the settings menu. **How many presets do you think you would need/use?** I may have to adjust the popup UI accordingly

I'm also in the process of redesigning the existing "custom choice" button from the janky datetime input form to a panel containing a fixed calendar and timepicker with better cross-browser and keyboard support. Nothing is set in stone, but I was maybe thinking about having some buttons like "1 hour from now" etc in this panel. This would be in addition to the custom presets I mentioned above.

**Comment by orschiro** [comment]
Hi Rohan,

With Snooze Tabby I am currently using 13 slots as shown in my example
above.

**Comment by concese** [comment]
On my side, the needs are not as extensive, and I usually use for short term (in the same day scenario). 
For longer periods, I'm comfortable with the tomorrow/next week /next month versions, and the custom date/time when needed. 

As for the custom choice:
- the calendar pick is very interesting (since you can also see directly what day of the week is)
- as for the time, I personally do not like the formats where you have to scroll up/down to choose the hour/minutes (even find it annoying for an UI, especially on desktop).  I actually prefer typing the time. 

thanks for the time invested and availability to accept input/requirements

**Comment by kstev99** [comment]
A lot of sweepstakes entry forms have a requirement of either Re-Enter in 24HRS or 6HRS.  I would love to see perhaps two or three slots where you could define a number of hours to snooze or even a Preset 6/24HRS Slot.  Currently using Tab Snooze which has ONE customizable slot for "LATER" ,Your add-on looks VERY nice and promising.  I hope that you will consider these custom time slot(s)

**Comment by kstev99** [comment]
> 
> 
> Just a quick Q for all you guys requesting this. I'm thinking of adding the ability to define custom preset times in the settings menu. **How many presets do you think you would need/use?** I may have to adjust the popup UI accordingly
> 
> I'm also in the process of redesigning the existing "custom choice" button from the janky datetime input form to a panel containing a fixed calendar and timepicker with better cross-browser and keyboard support. Nothing is set in stone, but I was maybe thinking about having some buttons like "1 hour from now" etc in this panel. This would be in addition to the custom presets I mentioned above.

Personally I think that 3-5 slots would be nice without overdoing it and making it cluttered

**Comment by rohanb10** [comment]
<img width="679" alt="Screenshot 2021-05-14 at 4 49 47 PM" src="https://user-images.githubusercontent.com/11708770/118265483-df763880-b4d6-11eb-8fa6-387862d6c815.png">

I have updated the "Choose your own time" option as a stopgap solution. I know its a lot of clicks, but hopefully this will make it a bit easier for now.

Eventually I hope to allow users to choose which options they want to see in the popup, so you would be able to define your own fixed choices

**Comment by orschiro** [comment]
@rohanb10 

> Eventually I hope to allow users to choose which options they want to see in the popup, so you would be able to define your own fixed choices

Any plans for that?

Yes, it's really still a lot of clicks...
