### ISSUE TITLE
Only unsnooze if internet ready

### ISSUE THREAD

**Issue by orschiro** [rohanb10/snoozz-tab-snoozing#23]
Hey! :)

Another great feature would be to wait with unsnoozing until internet is ready. 

Context:

If you wake up your computer from suspend, it takes a while sometimes for wifi to reconnect.

If tabs are unsnoozed during that moment, they all can't be properly loaded.

Thanks!

**Comment by rohanb10** [comment]
For performance related reasons, I can't add this right now  for all tabs.  There is a new [event type](https://developer.mozilla.org/en-US/docs/Web/API/Window/online_event) for detecting when the network status has changed, but it came out only a few months ago and [browser support](https://caniuse.com/mdn-api_window_online_event) is not as extensive as I would like (currently just below 70%). if it gets above 80-85%, I would be far more comfortable adding this feature in.

I have not spent a ton of time thinking about this, but if I figure out a way to get this done without the performance hit then I'll definitely add it in

**Comment by orschiro** [comment]
Sounds great, thanks!

**Comment by DrunkenCommie** [comment]
Psst. Browser support is now a "go"! :) Please do implement.
(you might just become the all-snooze-replacement for all)

**Comment by rohanb10** [comment]
going to try to wrap this up with the next release

**Comment by rohanb10** [comment]
This is out in v2.4.4
