### ISSUE TITLE
[BUG] Can't snooze tabs with local pages

### ISSUE THREAD

**Issue by concese** [rohanb10/snoozz-tab-snoozing#27]
## Description
Can't snooze a tab of local files. 
Many times I'm suspending several tabs, and forget that a specific one from a local file, for example file:///C:/Users/concese/lintalist/docs/index.html
When I want to snooze the tab of the local page, I accidentally snooze the complete window

## Expected Behavior
I should be able to snooze tabs from local html files

## Actual Behavior
I can only snooze the complete window.

## How to Reproduce (if applicable)
1. Open firefox
2. Open a couple of new tabs and load pages
3. Open a new tab and load a local html page
4. Click on the snooze button and try to snooze the tab

## Your Device
* Browser and version: Firefox 78.7.1esr (64-bit)
* OS: Windows 10 Enterprise

## Which Page
Local file, which have an url like file:///C:/Users/my-username/Downloads/WEB-page.html

## Screenshots / Videos / Logs
![snoozz - cant snooze tab from local file](https://user-images.githubusercontent.com/26224424/108520060-8a0cff80-72ca-11eb-90b1-540065383e4c.png)

**Comment by rohanb10** [comment]
Unfortunately this isnt possible for security reasons. I cannot get access to file urls on your computer. I dont think this will be possible to do.

If you know of any other extension that does this, please let me know and I'll try to reverse engineer it.
