### ISSUE TITLE
allow calendar window for "choose your own time"

### ISSUE THREAD

**Issue by DrunkenCommie** [rohanb10/snoozz-tab-snoozing#29]
## What would you like to change
Right now snoozing "choose your own time"
a) uses American date/time format (instead of whatever browser uses)
b) forces you to type date/time, instead of clickety-click

## What would you like to see instead
Use international / browser-specified date format.
Allow clickable calendar/clock, *apart* (not instead) of typing.

## Which browser / OS do you use
Firefox 86, Win 10

## Screenshots / Videos
is: picture 1
<img width="493" alt="choose-now" src="https://user-images.githubusercontent.com/41784423/110217971-04cf4080-7eaf-11eb-9bd6-4c5a3d8bfc53.png">
could be: picture 2
<img width="244" alt="could-be" src="https://user-images.githubusercontent.com/41784423/110217995-23353c00-7eaf-11eb-9970-0a6c23f60003.png">

**Comment by rohanb10** [comment]
Hello. I've completely rewritten the "choose your own time" choice. It will look like this across all browsers.
<img width="679" alt="Screenshot 2021-05-14 at 4 49 47 PM" src="https://user-images.githubusercontent.com/11708770/118263896-84dbdd00-b4d4-11eb-83cc-962955067111.png">

It will be published soon, after a bit more testing
