### ISSUE TITLE
[BUG] past "weekend" snooze time still an available option

### ISSUE THREAD

**Issue by mkeroppi** [rohanb10/snoozz-tab-snoozing#3]
**Device (please complete the following information):**
 - OS: Windows
 - Browser: firefox
 - Version: 81.0.1

**Which Page**
Where did you find the bug:  [Popup / Dashboard / Settings]
all

**What went wrong**
"weekend" snooze time that's in the past is still an available option (not blacked out or changed to next weekend)

**Screenshots**
If you can, add screenshots to help explain your problem.

**If you know how, can you open up your browser console and copy+paste any errors/warnings here**

**Comment by rohanb10** [comment]
Fixed https://github.com/rohanb10/snoozz-tab-snoozing/commit/ffcb32cde4df7e414c6343a160233e0c166e45e1

I'm a dingo. I had code for this but it was commented out 🤦

**Comment by rohanb10** [comment]
Bug has been fixed in v2.1.2
