### ISSUE TITLE
[FEATURE] snooze until "next open"

### ISSUE THREAD

**Issue by michaljenicek** [rohanb10/snoozz-tab-snoozing#30]
##  Description
I love your extension, but one feature I am missing is the ability to snooze tab until next open of the browser. Basically the tab opens next time you start the browser.

## Context
It would be useful for example when you encounter some article that you want to read later, but are currently working on something so you don't want to get distracted, so you snooze it until next open.

## Possible Implementation
For example the [Snooze Tabs](https://addons.mozilla.org/en-US/firefox/addon/snoozetabs/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) extensions offers this feature and I loved it, but decided to switch for different reasons.

## Your Setup
firefox

**Comment by rohanb10** [comment]
This is a great idea. Just need to figure out how to implement this in the UI and I'll get it done

**Comment by rohanb10** [comment]
All done. Will be pushed with the next release soon
<img width="681" alt="Screenshot 2021-05-15 at 6 18 53 PM" src="https://user-images.githubusercontent.com/11708770/118361779-7eb83000-b5aa-11eb-9acc-6f5bbf814137.png">

**Comment by michaljenicek** [comment]
Awesome, love it! Thanks a lot!
