### ISSUE TITLE
24 hour format

### ISSUE THREAD

**Issue by hodanli** [rohanb10/snoozz-tab-snoozing#33]
it would be nice to have 24 hour format. 

best.

**Comment by rohanb10** [comment]
Will make sure this is finished in the next update

**Comment by rohanb10** [comment]
Just added this in. Need to test it a bit more before I feel comfortable releasing a new version

**Comment by rohanb10** [comment]
This is in Snoozz 2.4.2. its been published in chrome and ff stores. Let me know if everything is ok
