### ISSUE TITLE
Default to "Selected" if multiple tabs selected

### ISSUE THREAD

**Issue by AnttiBoman** [rohanb10/snoozz-tab-snoozing#35]
If I select multiple tabs and click the Snoozz toolbar button, the default is to snooze only the active tab. IMO, the more intuitive default would be to automatically have the "Selected" option chosen.

Snoozz version: 2.4.2.1
Browser: Firefox 89.0, 64-bit
OS: Ubuntu 20.04.2 LTS, 64-bit

**Comment by rohanb10** [comment]
This makes a lot of sense. Just pushed a new commit to do this. Will be out with the next release

**Comment by AnttiBoman** [comment]
@rohanb10 Sorry, accidentally closed the issue. Thank you for the extremely quick response and fix, and for the great extension!

**Comment by rohanb10** [comment]
No worries at all. This is live on firefox now in v2.4.3
