### ISSUE TITLE
Disable notifications?

### ISSUE THREAD

**Issue by orschiro** [rohanb10/snoozz-tab-snoozing#36]
Hey guys!

Maybe I simply missed it but where is the option to disable notifications on unsnoozing?

**Comment by rohanb10** [comment]
Funnily enough, I just added this feature yesterday. It will be out with the next release soon

**Comment by orschiro** [comment]
Wow, great! :)

**Comment by rohanb10** [comment]
this change is released on firefox. awaiting review on chrome and will be out in 12ish hours i think

**Comment by orschiro** [comment]
Wow, thanks!
