### ISSUE TITLE
[ANNOUNCEMENT] Click Analytics

### ISSUE THREAD

**Issue by rohanb10** [rohanb10/snoozz-tab-snoozing#39]
Starting with version 2.4.3, Snoozz will be collecting Click Analytics in the popup menu.

I am starting to collate the option you click when you a snooze a tab - "In One Hour", "Next Monday" etc. This will allow me to see which options are being used the most and help me make decisions in the future when creating new options. 

No other data is gathered. I don't track what you are snoozing, location, your IP address, language, browser, OS. I am only here for a single string of click data.

**All** collected data is uploaded to my [own](https://stats.snoozz.me) server on the Snoozz website. I have written a tiny API  (which is also [open source](https://github.com/rohanb10/snoozz-stats)), and you can view every single click on the [Stats page](http://snoozz.me/stats.html). There is no data processing or anything happening behind the scenes, so the stats on that page will update almost instantly.

All the code for this change is located in a new file called [`/scripts/poll.js`](https://github.com/rohanb10/snoozz-tab-snoozing/blob/master/scripts/poll.js), but theres so little code so I'm also reposting it below. As you can see, I am only sending the `choice` you have selected, nothing else - not even a timestamp. You can check out 

<p align="center">
<img src="https://user-images.githubusercontent.com/11708770/121773482-e3f74500-cb99-11eb-824c-fb5e6d9a6e0d.png">
</p>

This `poll(...)` function is only called once from the background page [`/scripts/background.js`](https://github.com/rohanb10/snoozz-tab-snoozing/blob/master/scripts/background.js#L4-L7). It is only triggered from the Snoozz popup [`/scripts/popup.js`](https://github.com/rohanb10/snoozz-tab-snoozing/blob/master/scripts/popup.js#L292) when you snooze (or edit) a tab/window. It is done in the background to ensure that the speed of the extension is not compromised. If you are offline at the time of snoozing no data will be transmitted - even when your re-connect later.

There is a new setting to toggle this on/off. It will be on by default.

I've never built something like this before so let me know if I've done something wrong.

**Comment by ghobs91** [comment]
I appreciate the transparency and clarity!

**Comment by ahmadawais** [comment]
This level of transparency is not only helpful but commendable. Thank you! 🙌
