### ISSUE TITLE
[BUG] snooze delay timer conflicts with other behavior

### ISSUE THREAD

**Issue by mkeroppi** [rohanb10/snoozz-tab-snoozing#4]
**Device (please complete the following information):**
 - OS: Windows
 - Browser: firefox
 - Version: 80.0.1

**Which Page**
Where did you find the bug:  [Popup / Dashboard / Settings]
all

**What went wrong**
Snooze delay timer conflicts with other behavior (e.g., duplicate tabs closer).  If a snooze tab reopens immediately (e.g., weekend time in the past is not blacked-out), the new duplicate tab is immediately closed by duplicate tabs closer, but the original tab is also closed later by snooze when the delay timer expires, which results in both tabs being closed.

Is there a need for the snooze delay timer at all.  The delay is not convenient for batch closing of tabs.  This was raised in a closed bug report.
**Screenshots**
If you can, add screenshots to help explain your problem.

**If you know how, can you open up your browser console and copy+paste any errors/warnings here**

**Comment by rohanb10** [comment]
The delay was originally introduced when some users complained that closing the tab immediately was a bit jarring and led to a bit of confusion if anything actually happened, or the extension bugged out.

But seeing as this complaint is coming up again and again, it might make sense to keep the delay behind a user setting. If you don't like or want the delay at all, you can disable it completely.

The behaviour you described above is also related to #3 and should not be happening in the first place. It shouldn't be possible to snooze tabs to times in the past at all and I will add additional checks to prevent that from ever happening.

**Comment by rohanb10** [comment]
TODO
1. Allow popup close delay to be disabled completely on the settings page. (Enabled by default, but this could be changed later)

**Comment by rohanb10** [comment]
A new option to control popup delay was added in this commit https://github.com/rohanb10/snoozz-tab-snoozing/commit/99c56276cab36426b9e296049c7d9469bfbb4bf3

Three options are available: Normal delay (2s), Short Delay (1s) and none.

Last round of testing and hoping to release this within the next 24 hours

**Comment by rohanb10** [comment]
Bug has been fixed in v2.1.2
