### ISSUE TITLE
[BUG] Calendar picker: show day of the week

### ISSUE THREAD

**Issue by concese** [rohanb10/snoozz-tab-snoozing#40]
## What would you like to change
Calendar picker does not show the day of the week

## What would you like to see instead
Day of the week, on the top of the calendar. It could be with smaller font if it makes easier to read

## What is your specific use case (if applicable)
Personally I prefer to use Monday as the first day of the week. 
Since not all systems allow this configuration, it may be confusing to know which day of the week is, when picking a date on the calendar.

## Which browser / OS do you use
Windows 10
Firefox 78.11.0esr (64-bit)

## Screenshots / Videos
![snoozz - calendar picker 2021-06-21 10_17_21-Window](https://user-images.githubusercontent.com/26224424/122731586-bd14cf00-d27b-11eb-8581-3b4ce9d983c2.png)

**Comment by rohanb10** [comment]
Something like this?
<img width="713" alt="Screenshot 2021-06-21 at 2 14 16 PM" src="https://user-images.githubusercontent.com/11708770/122733672-0294c480-d29b-11eb-8719-e479e4414b98.png">

I can also add a "Week Starts on" setting so you can switch it to Monday

**Comment by rohanb10** [comment]
The missing weeks was a bug introduced in 2.4.3

I have reverted it for now. Will push it out with that new Setting soon.

**Comment by rohanb10** [comment]
v2.4.4.2 is out in the ff store with this fixed.
Theres also a new setting to choose the start day of your week
