### ISSUE TITLE
Snooze selected should/could group them like when snoozing a window

### ISSUE THREAD

**Issue by AnttiBoman** [rohanb10/snoozz-tab-snoozing#41]
I like the grouping of tabs when snoozing a window. It's easy to wake them up manually or adjust the date and time for all of them. This could happen if snoozing multiple tabs via Selected, too! It's also a more logical way, as window is just a group of tabs.

Thanks, again!

**Comment by rohanb10** [comment]
Sounds good to me. Will make this change and push it out with the next release.

Currently when a snoozed window wakes up, it will open in a tab. For snoozed selections, I will open it up in any existing window, or create a new one if no window exists.

🍻 for the beer :)

**Comment by AnttiBoman** [comment]
Thanks, and cheers for an excellent addition to the idea! Have a great 🍺 !

**Comment by rohanb10** [comment]
This is ready and will be pushed out in v4.5.0. Selected tabs are saved in a similar way that windows are, but they reopen just like any other individual tabs. You can edit/duplicate the selected tabs as a group now.


<img width="1188" alt="Screenshot 2021-07-29 at 5 27 37 AM" src="https://user-images.githubusercontent.com/11708770/127411124-cba7671e-22f5-4e8d-afd5-0629ddd0f2cf.png">

**Comment by rohanb10** [comment]
Snoozed selections are now grouped together with v2.5
