### ISSUE TITLE
[BUG] Keyboard Shortcuts are Not Working In Firefox

### ISSUE THREAD

**Issue by typkrft** [rohanb10/snoozz-tab-snoozing#44]
## Description
In settings when trying to configure keyboard shortcuts it states `Configure snooze time shortcuts on the Extension Shortcuts page` However as far as I can tell snooze times are setup. When you click on the`Extension Shortcuts` link. It just brings me to the top of the page. Am I missing something?

## Expected Behavior
Click Configure Keyboard Shortcuts then see a way to configure keybindings. 

## Your Device
* Browser and version: Firefox 91.0b6 (64-bit)
* OS: macOS 11.3 (20E232)
* Resolution: 3360 x 2100

## Which Page

Settings

**Comment by typkrft** [comment]
I've just noticed as well that right clicking on tabs does not show the extension in the context menu. Right clicking a link does though.

**Comment by typkrft** [comment]
Well I just realized saw this lol.

```HTML
			<div class="mini firefox-info">
				<strong>Instructions</strong>
				<ol>
					<li>Open the Firefox Add-Ons page in a new tab: <u><code>about:addons</code></u>.</li>
					<li>Click on the <a tabindex="0" target="_blank" href="https://bug1303384.bmoattachments.org/attachment.cgi?id=9051647">gear icon</a> in the top right and select <strong>Manage Extension Shortcuts</strong>.</li> 
					<li>Configure snooze time shortcuts using your own key bindings.</li>
				</ol>
			</div>
```
I didn't realize Firefox had a unified way of handling extensions key bindings. Maybe it would be worth adding those instructions to the message. Thanks for for your work on this. The right clicking of tabs isn't working at the moment for me, but maybe I'm missing something again. I'll close this though because that's a different issue.

**Comment by rohanb10** [comment]
hey @typkrft could you try toggling any of the context menu items on and off? that will reset the context menu setup and might fix your issue. if not ill download the ff beta and check it out

<img width="459" alt="image" src="https://user-images.githubusercontent.com/11708770/126877388-9beacd84-30a4-46c1-a51c-a0facf78a87c.png">

**Comment by rohanb10** [comment]
and yeah sorry about the Firefox shortcuts thing. its a bit confusing and there's been an bug open for almost two years to make it a similar to the way chrome has done it. I will try to word it a bit better to reduce confusion

https://bugzilla.mozilla.org/show_bug.cgi?id=1538451

in chrome I just can open `chrome://extensions/shortcuts` in a new tab and open up the keybindings page.

**Comment by typkrft** [comment]
Hey no worries, It's very possible I'm just an ignoramus. I did try toggling on and off the context menu selections as requested to no avail. But it's no huge deal, for me at least. Firefox makes some odd design choices sometimes, it's often my favorite browser and my least favorite browser simultaneously. Regardless thank you for the great extension.
