### ISSUE TITLE
[FEATURE] Snooz an extension page

### ISSUE THREAD

**Issue by Nwardezir** [rohanb10/snoozz-tab-snoozing#46]
##  Description
Possibility to add a chrome-extension generated page to the Snooz list

## Context

Example: with an extension like Session Buddy, I could have it opened at a specifi day/time
My use-case: start a pack of tabs every workday morning

## Possible Implementation

Just allow to put in Snooz an url that looks like
chrome-extension://yadayada

## Your Setup

Chrome

**Comment by Nwardezir** [comment]
Ok, quick update, this one may be merged with https://github.com/rohanb10/snoozz-tab-snoozing/issues/42

**Comment by rohanb10** [comment]
Yup a change has already been made to allow this. Will roll out in v2.5 whenever it's out
