### ISSUE TITLE
[FEATURE] Option to open a tab on periodic basis

### ISSUE THREAD

**Issue by jetm** [rohanb10/snoozz-tab-snoozing#49]
Thank you for this extension. It's looking like the best alternative to the Tab Snooze extension. 

##  Description

Snooze tabs are expected to open periodically. The user defines the period.

## Context

There are pages that a user periodically visits. It helps to avoid snooze again, and again pages are visited regularly. 

## Possible Implementation

Feature implemented in Tab Snooze:
<img width="298" alt="Tab Snooze" src="https://user-images.githubusercontent.com/474838/129455299-8d293608-ee27-4fb3-a143-14021b5a5e77.png">

## Your Setup

I use Chrome.

**Comment by Nwardezir** [comment]
It's planned with v2.5 coming this month (omg, can't wait! 🎉)

Funny as I did almost the same request 😉 https://github.com/rohanb10/snoozz-tab-snoozing/issues/48

**Comment by gniting** [comment]
@rohanb10 Came here looking for a replacement for the popular "Tab Snooze" as the recent 94.x release of Chrome has broken it. Then I saw that the devs had not updated that extension since 2019! 😮

Loving your work so far but really wanting "periodic reopen." Release notes say that it's in the works in v2.5 scheduled for Aug... in the past.  v2.5 still in the works?

**Comment by Nwardezir** [comment]
@gniting if you find an extension that does it, please drop me a line, I'm looking for a "Tab Snooze" replacement for months.

**Comment by gniting** [comment]
> @gniting if you find an extension that does it, please drop me a line, I'm looking for a "Tab Snooze" replacement for months.

snoozz is really good, just missing that one feature. Haven't found anything else... yet.

**Comment by Nwardezir** [comment]
@gniting oh I agree, it is definitely promising but unfortunately, it seems dev has gone into hiatus. I'm watching here for months, even emailed to offer help weeks ago and never got an answer.

**Comment by gniting** [comment]
> @gniting oh I agree, it is definitely promising but unfortunately, it seems dev has gone into hiatus. I'm watching here for months, even emailed to offer help weeks ago and never got an answer.

oh, that is indeed unfortunate. Can always fork the project and make your own ;)

**Comment by Nwardezir** [comment]
[Forked one month ago.](https://github.com/rohanb10/snoozz-tab-snoozing/network/members)

**Comment by SullieLore** [comment]
> [Forked one month ago.](https://github.com/rohanb10/snoozz-tab-snoozing/network/members)

I can't see any releases for the commits. Is there a way to add the extra coding to the existing release extension from the Chrome extension? Thanks for any info; the recurring tabs feature is sorely missed.

**Comment by rohanb10** [comment]
Hey guys, sorry for disappearing. Cut my hand really bad and been unable to type.

I have a beta version with recurring tabs. Will push out on the github releases page within the next 12 hours. Please fork it from there, or just help me test it out. It's one of the most requested features so I'm really hoping to get it out.

**Comment by gniting** [comment]
@rohanb10 sorry to hear that and glad that you're better now. Ping me when it is pushed to a dev branch along with any install instructions and I'll be happy to test.

As you know, the ever so popular "Tab Snooze" extension unexpectedly died with the latest chrome 94.x update and their users are clamoring for a replacement. The dev team there is not responding.

You have an oppty here to invite all those users over to your work.

**Comment by Nwardezir** [comment]
I confirm there is an opportunity as dev of snoozetabby.com also gone silent and extension seems not to be supported either (yeah, I confess, I tried 3 or 4 other extensions when I've seen snooz.me wasn't responding 😁)

**Comment by rohanb10** [comment]
Hey all, fixed the last major known bug with recurring snoozes (duplicating and editing existing snoozed tabs).
I've published a version on the releases page. If you are trying to fork this repo, I'd suggest using the `repeat` branch since it contains all the recurring snooze changes.

I will be testing extensively and hope to release this in all the extension stores within the next ~7 days

You can download this release here: https://github.com/rohanb10/snoozz-tab-snoozing/releases/tag/v2.5.0-beta

**Comment by rohanb10** [comment]
This has finally been released publicly with v2.5 this morning 🎉 

Please create a new issue if you run into any bugs or snafus
