### ISSUE TITLE
[BUG] selecting "report a bug" option in "settings" does not report new bugs past the first one

### ISSUE THREAD

**Issue by mkeroppi** [rohanb10/snoozz-tab-snoozing#5]
**Device (please complete the following information):**
 - OS: Windows
 - Browser: firefox
 - Version: 80.0.1

**Which Page**
Where did you find the bug:  [Popup / Dashboard / Settings]
Settings

**What went wrong**
Clicking on it reports the first bug.  Clicking on it again opens the bug report page but does not actually submits the bug report when actually submitting.

May be something wrong with github and the link "https://github.com/rohanb10/snooze/issues/new?assignees=rohanb10&labels=&template=bug-report.md&title=%5BBUG%5D"

**Screenshots**
If you can, add screenshots to help explain your problem.

**If you know how, can you open up your browser console and copy+paste any errors/warnings here**

**Comment by rohanb10** [comment]
Was doing some spring cleaning and reorganisation in the repo and may have accidentally deleted a file. This will definitely be fixed in the next update. Should be a simple `href` fix

**Comment by rohanb10** [comment]
Fixed https://github.com/rohanb10/snoozz-tab-snoozing/commit/024d9d4f9418dbc975a349e92143bbdb248049fc

**Comment by rohanb10** [comment]
Bug has been fixed in v2.1.2
