### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by nathangilchrist** [rohanb10/snoozz-tab-snoozing#53]
##  Description
Selecting this feature opens a tab that would allow the user to type a note in and snooze for future recall.

## Context
Users who use Snoozz religiously and could benefit from a bit of task management.
This would be a feature that could be utilized but would otherwise sit in the sidelines until needed.

## Possible Implementation
Simple text entry is sufficient, but allowing the inclusion of Markdown formatting would be a bonus.
Tab Snooze currently allows text-only entry into a tab window that cycles between 4 colors when the Tab key is pressed.

## Your Setup
Chrome 94 beta

**Comment by Nwardezir** [comment]
Can be merged with https://github.com/rohanb10/snoozz-tab-snoozing/issues/47 I guess.
