### ISSUE TITLE
[FEATURE] Implement a custom time/date picker for the "Choose your own time" button

### ISSUE THREAD

**Issue by RandomClaim** [rohanb10/snoozz-tab-snoozing#6]
## Description
"Choose your own Time" Option is not working. I can't choose the Dates

## Expected Behavior
Works fine on the chrome version, so similar to that.

## Actual Behavior
The current date and time are shown as plain text when clicking the button.

## Your Device.
* Browser and version: Firefox 81.0.1
* OS: Windows 10 2004
* Device Resolution (UI related bugs only)

## Screenshots / Videos / Logs
![Screenshot 2020-10-08 103215](https://user-images.githubusercontent.com/9338392/95434479-97e06a80-0951-11eb-99a9-8cad902934eb.png)

I really like you addon so far (only found out about it 2 days ago), thanks a lot for it!

**Comment by rohanb10** [comment]
Hmm I'm not quite able to reproduce this on my end. 

Can you let me know what happens when you click on either the time or date? Is an individual section (ie. Month/Year) highlighted or is it like a regular text input

**Comment by rohanb10** [comment]
PS: thanks for letting me know about those extra scrollbars in the screenshot. Will have a fix for that in the next release

**Comment by RandomHam** [comment]
Okay, I just checked again and the values are in fact changeable for me. However, only via keyboard input while having the field selected. So basically the pop-up from the chromium version is missing. Sorry the false claim!

As to your question, single-clicking a field marks it just like a double-click would for normal text. After that the field can be changed.

![Screenshot 2020-10-08 104312](https://user-images.githubusercontent.com/9338392/95435607-14277d80-0953-11eb-870a-29bbb6607e43.png)

FYI: the scrollbars also appear on chromium ("Version 84.0.4147.135 (Developer Build) (64-bit)") for me, but that did not really bother me yet to be honest.

**Comment by rohanb10** [comment]
No worries at all. It isn't exactly broken, but it's something I can improve for sure. 

I'm using the standard [date](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date) and [time](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time) `input` fields, but I've customised a lot of the style and behaviour. If you open those two links on firefox and click on the inputs in the demo, you will see a popup in firefox too which I've disabled somehow. Going to figure out how to undo that.

As for the scrollbars, I can't really reproduce them on my computer. But i think I know of some css tricks that will hopefully (🤞 ) hide them.

**Comment by rohanb10** [comment]
I have some bad news. I disabled all css / js in the extension popup and tried to open the date "panel" on firefox and it never opened. Did some googling and found this post in the firefox forums

[https://discourse.mozilla.org/t/webextensions-date-input-element-in-browser-action-does-not-work-in-desktop/27114](https://discourse.mozilla.org/t/webextensions-date-input-element-in-browser-action-does-not-work-in-desktop/27114)

Unfortunately, the way popups work in firefox - you cannot have a panel inside a popup. The `date`/`time` picker panels that you normally see when you click their input fields are considered popups. This functionality also is missing when you try other input types which require popups like `color` or `file`.

Nothing I can do unless firefox fixes this internally. Here is an issue I found in bugzilla that I think covers this:

[https://bugzilla.mozilla.org/show_bug.cgi?id=1450473](https://bugzilla.mozilla.org/show_bug.cgi?id=1450473)

If this is ever fixed I will reopen this issue

**Comment by RandomHam** [comment]
Ah that's bad to hear! 
Would it be possible to make the content of the selected field scroll-able (using the mouse wheel)? that would make it more convenient to use, at least to me. 
Another idea would be to make it more clear visually that the text is not just marked but actually selected as a field.
Lastly, it might be better to let the user just pick a single-predefined custom time from the settings menu which triggers automatically when using that button, but that is probably a lot of work to rewrite it.

I don't how hard that is to implement, so feel free to ignore that. I just think that in its current state it might be confusing to figure out (see my initial post) to new users. The extension is great anyways and I'm thankful for your work!

**Comment by rohanb10** [comment]
> Would it be possible to make the content of the selected field scroll-able (using the mouse wheel)? that would make it more convenient to use, at least to me.
Don't have a mouse unfortunately, but will try to borrow one and try this out. Seems like a decent compromise.

> Another idea would be to make it more clear visually that the text is not just marked but actually selected as a field.

Will try to work something out for this. Makes sense to me

> Lastly, it might be better to let the user just pick a single-predefined custom time from the settings menu which triggers automatically when using that button, but that is probably a lot of work to rewrite it.

Yup this is definitely on the radar. The next major release is going to allow more customisation for the choices you see when you open up the popup. Will require a lot of testing though so will probably be a while till this gets done

**Comment by rohanb10** [comment]
Honestly really frustrated with the way to choose a custom time+date in FF. I'm looking out for a lightweight 3rd party component which has a clean intuitive UI for a time/date picker. Will potentially hide this behind a "modal" for the custom choice button

Reopening this.

**Comment by hodanli** [comment]
i think the way [this](https://github.com/bwinton/SnoozeTabs#readme) add-0n lets us to choose the date fits the purpose.

**Comment by rohanb10** [comment]
I have added [flatpickr](https://github.com/flatpickr/flatpickr) to the extension behind the "choose your own time" option. 

<img width="679" alt="Screenshot 2021-05-14 at 4 49 47 PM" src="https://user-images.githubusercontent.com/11708770/118378963-e004f100-b5f4-11eb-941f-4f3ab4c3c496.png">

Have made a lot of other changes too for v2.4.0 so still need to test quite a bit before I can push it out the stores. Theres a pre-release version uploaded to this repo if anyone wants to manually install it
