### ISSUE TITLE
[CHANGE] option to default next week or month to morning hours

### ISSUE THREAD

**Issue by mkeroppi** [rohanb10/snoozz-tab-snoozing#8]
## What would you like to change
current next week or month option is for the same time as the current time

## What would you like to see instead
option to default next week or month to morning hours to be consistent with weekend and next monday

## What is your specific use case (if applicable)
for consistent tab wake time behavior

## Which browser / OS do you use
Windows/firefox

**Comment by rohanb10** [comment]
Fixed https://github.com/rohanb10/snoozz-tab-snoozing/commit/30d62432aa36ac5402cd5e4ae7e0745244366a11

**Comment by rohanb10** [comment]
Change has been made in v2.2.0
