### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by rayvermey** [rohanb10/snoozz-tab-snoozing#88]
##  Description

I would like to auto snooze a tab between certain times, for instance my Work Mail Tab would
be only active between 09am and 6pm
## Context

Users who only want to see certain tabs during working hours
## Your Setup

Vivaldi/chrome/firefox

**Comment by rohanb10** [comment]
Hi @rayvermey . I'm not sure what you mean by auto snooze a tab. Can you please elaborate?

Snoozz cannot close tabs for you. It will only reopen them at the specified time

Sorry for the extremely delayed response.

**Comment by rayvermey** [comment]
Hi

well, i would like to have my enail for work tab automatically snooze from
17:00 till 09:00 during workdays and 00:00 - 24:00 in the weekends.

Ray

Op za 5 mrt. 2022 om 09:47 schreef Rohan ***@***.***>:

**Comment by rohanb10** [comment]
Hi Ray,
As mentioned earlier, Snoozz cannot close any tabs. You can Snoozz your work email tab once to reopen automatically every weekday morning at 9am, but you will have to close it yourself every weekday at 5pm. 

This functionality is already built in and can be accessed using the "Repeat ?" button in the extension popup
