### ISSUE TITLE
[FEATURE] keyboard shortcut support

### ISSUE THREAD

**Issue by mkeroppi** [rohanb10/snoozz-tab-snoozing#9]
##  Description

keyboard shortcut support for certain snooze time (e.g., Times in enable Snoozz in the right-click (context) menu)

## Context

Times in enable Snoozz in the right-click (context) menu

## Possible Implementation

Ctrl-Shift-1 to -5 seems open, but doesn't really matter.

## Your Setup

firefox

**Comment by rohanb10** [comment]
To clarify, you would like to enter a keyboard shortcut when the rightclick/context menu is open? Or do you mean the popup when you click on the extension icon in the toolbar.

I don't really see the benefit of a keyboard shortcut if you already have to use a mouse/trackpad to open the context menu. Is there a keyboard shortcut to open the context menu? 

I don't have a lot of knowledge about keyboard shortcuts and accessibility in general. Its something I definitely will work on soon.

StackOverflow - [Firefox keyboard shortcuts to menu items / add-on functions
](https://superuser.com/questions/446073/firefox-keyboard-shortcuts-to-menu-items-add-on-functions)

**Comment by mkeroppi** [comment]
I mean it would just snooze the current tab (without opening any menus) when the shortcut is entered.

**Comment by rohanb10** [comment]
Added this feature. https://github.com/rohanb10/snoozz-tab-snoozing/commit/61202a57ab74952c92b2b18216830d957bcc09b1

Thanks for the idea @mkeroppi . really happy with how its turned out

**Comment by rohanb10** [comment]
Feature is live in v2.2.0
