### ISSUE TITLE
Hi. I love Snoozz! (I use the Chrome Extension.) The one feature I would love to see is the ability to Snoozz multiple tabs at once. If this already exists, I couldn't find any reference to it in the documentation. Thank you!

### ISSUE THREAD

**Issue by ibiwisi** [rohanb10/snoozz-tab-snoozing#93]

**Comment by rohanb10** [comment]
Hi @ibiwisi . This is already possible. You can press the ctrl (windows) or cmd (mac) key on your keyboard + and then click on the tabs you would like to snoozz to select multiple tabs. If you open the Snoozz popup with multiple tabs selected, you will be able to see the "Selected" option and do what you are asking for.

See here for more details about [tab selection](https://www.ghacks.net/2018/08/29/how-to-select-and-move-multiple-chrome-tabs-at-once/#:~:text=Select%20multiple%20tabs%20in%20Chrome&text=All%20you%20have%20to%20do,select%20a%20set%20of%20tabs.) in Chrome

**Comment by ibiwisi** [comment]
Thank you so much, Rohan -- it worked! It was really easy. Sorry to
trouble you with this. If I may offer a humble suggestion, I'll be a lot of
Snoozz customers would like to know about this feature -- you might put
something on the website explaining it. Thanks again for your help with
this.  Regards, Michael

*________________*

*Michael Shpizner*
M:  (408) 464-6030
E:  ***@***.*** ***@***.***>*
*_________________*
